# CMake generated Testfile for 
# Source directory: /home/vaibhav/Documents/LFX_Selection_Work/arpack-ng
# Build directory: /home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(cnbdr1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/cnbdr1")
set_tests_properties(cnbdr1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;467;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cnbdr2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/cnbdr2")
set_tests_properties(cnbdr2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;467;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cnbdr3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/cnbdr3")
set_tests_properties(cnbdr3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;467;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cnbdr4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/cnbdr4")
set_tests_properties(cnbdr4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;467;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnbdr1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dnbdr1")
set_tests_properties(dnbdr1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;477;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnbdr2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dnbdr2")
set_tests_properties(dnbdr2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;477;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnbdr3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dnbdr3")
set_tests_properties(dnbdr3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;477;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnbdr4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dnbdr4")
set_tests_properties(dnbdr4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;477;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnbdr5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dnbdr5")
set_tests_properties(dnbdr5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;477;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnbdr6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dnbdr6")
set_tests_properties(dnbdr6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;477;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsbdr1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dsbdr1")
set_tests_properties(dsbdr1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;487;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsbdr2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dsbdr2")
set_tests_properties(dsbdr2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;487;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsbdr3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dsbdr3")
set_tests_properties(dsbdr3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;487;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsbdr4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dsbdr4")
set_tests_properties(dsbdr4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;487;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsbdr5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dsbdr5")
set_tests_properties(dsbdr5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;487;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsbdr6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/dsbdr6")
set_tests_properties(dsbdr6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;487;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snbdr1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/snbdr1")
set_tests_properties(snbdr1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;497;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snbdr2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/snbdr2")
set_tests_properties(snbdr2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;497;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snbdr3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/snbdr3")
set_tests_properties(snbdr3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;497;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snbdr4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/snbdr4")
set_tests_properties(snbdr4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;497;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snbdr5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/snbdr5")
set_tests_properties(snbdr5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;497;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snbdr6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/snbdr6")
set_tests_properties(snbdr6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;497;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssbdr1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/ssbdr1")
set_tests_properties(ssbdr1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;507;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssbdr2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/ssbdr2")
set_tests_properties(ssbdr2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;507;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssbdr3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/ssbdr3")
set_tests_properties(ssbdr3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;507;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssbdr4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/ssbdr4")
set_tests_properties(ssbdr4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;507;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssbdr5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/ssbdr5")
set_tests_properties(ssbdr5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;507;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssbdr6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/ssbdr6")
set_tests_properties(ssbdr6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;507;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(znbdr1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/znbdr1")
set_tests_properties(znbdr1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;515;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(znbdr2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/znbdr2")
set_tests_properties(znbdr2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;515;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(znbdr3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/znbdr3")
set_tests_properties(znbdr3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;515;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(znbdr4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/BAND/znbdr4")
set_tests_properties(znbdr4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;515;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cndrv1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/cndrv1")
set_tests_properties(cndrv1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cndrv2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/cndrv2")
set_tests_properties(cndrv2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cndrv3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/cndrv3")
set_tests_properties(cndrv3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cndrv4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/cndrv4")
set_tests_properties(cndrv4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(zndrv1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/zndrv1")
set_tests_properties(zndrv1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(zndrv2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/zndrv2")
set_tests_properties(zndrv2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(zndrv3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/zndrv3")
set_tests_properties(zndrv3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(zndrv4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/COMPLEX/zndrv4")
set_tests_properties(zndrv4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;533;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dndrv1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/dndrv1")
set_tests_properties(dndrv1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dndrv2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/dndrv2")
set_tests_properties(dndrv2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dndrv3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/dndrv3")
set_tests_properties(dndrv3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dndrv4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/dndrv4")
set_tests_properties(dndrv4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dndrv5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/dndrv5")
set_tests_properties(dndrv5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dndrv6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/dndrv6")
set_tests_properties(dndrv6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sndrv1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/sndrv1")
set_tests_properties(sndrv1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sndrv2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/sndrv2")
set_tests_properties(sndrv2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sndrv3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/sndrv3")
set_tests_properties(sndrv3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sndrv4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/sndrv4")
set_tests_properties(sndrv4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sndrv5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/sndrv5")
set_tests_properties(sndrv5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sndrv6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/NONSYM/sndrv6")
set_tests_properties(sndrv6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;554;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(cnsimp_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SIMPLE/cnsimp")
set_tests_properties(cnsimp_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;570;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnsimp_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SIMPLE/dnsimp")
set_tests_properties(dnsimp_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;570;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dssimp_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SIMPLE/dssimp")
set_tests_properties(dssimp_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;570;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(snsimp_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SIMPLE/snsimp")
set_tests_properties(snsimp_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;570;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(sssimp_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SIMPLE/sssimp")
set_tests_properties(sssimp_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;570;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(znsimp_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SIMPLE/znsimp")
set_tests_properties(znsimp_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;570;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssvd_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SVD/ssvd")
set_tests_properties(ssvd_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;581;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsdrv1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/dsdrv1")
set_tests_properties(dsdrv1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsdrv2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/dsdrv2")
set_tests_properties(dsdrv2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsdrv3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/dsdrv3")
set_tests_properties(dsdrv3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsdrv4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/dsdrv4")
set_tests_properties(dsdrv4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsdrv5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/dsdrv5")
set_tests_properties(dsdrv5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dsdrv6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/dsdrv6")
set_tests_properties(dsdrv6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssdrv1_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/ssdrv1")
set_tests_properties(ssdrv1_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssdrv2_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/ssdrv2")
set_tests_properties(ssdrv2_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssdrv3_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/ssdrv3")
set_tests_properties(ssdrv3_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssdrv4_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/ssdrv4")
set_tests_properties(ssdrv4_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssdrv5_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/ssdrv5")
set_tests_properties(ssdrv5_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(ssdrv6_ex "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/EXAMPLES/SYM/ssdrv6")
set_tests_properties(ssdrv6_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;66;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;603;examples;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(dnsimp_tst "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/TESTS/dnsimp")
set_tests_properties(dnsimp_tst PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;655;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;816;build_tests;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(bug_1323_tst "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/TESTS/bug_1323")
set_tests_properties(bug_1323_tst PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;671;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;816;build_tests;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(bug_58_double_tst "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/TESTS/bug_58_double")
set_tests_properties(bug_58_double_tst PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;675;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;816;build_tests;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(bug_79_double_complex_tst "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/TESTS/bug_79_double_complex")
set_tests_properties(bug_79_double_complex_tst PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;679;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;816;build_tests;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(bug_142_tst "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/TESTS/bug_142")
set_tests_properties(bug_142_tst PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;683;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;816;build_tests;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
add_test(bug_142_gen_tst "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/_build_riscv64/TESTS/bug_142_gen")
set_tests_properties(bug_142_gen_tst PROPERTIES  _BACKTRACE_TRIPLES "/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;687;add_test;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;816;build_tests;/home/vaibhav/Documents/LFX_Selection_Work/arpack-ng/CMakeLists.txt;0;")
